# tftpd image for the TDD Project.

ARG DOCKER_FROM

FROM ${DOCKER_FROM}

ENV LANG='C.UTF-8' \
	LC_ALL='C.UTF-8' \
	TDD_TFTP_SERVER='1' \
	TDD_TFTP_SERVER_ALPINE='1'

RUN apk add --update tftp-hpa \
	&& rm -rf /tmp/* /var/tmp/*

EXPOSE 69/udp

CMD ["/usr/sbin/in.tftpd","--verbosity=3","--foreground","--secure","--ipv4","/tftproot"]
